// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8iBt5PfoZi7CilNnyqmBa0ovZnOYQHsw',
    appId: '1:186697788898:web:e49960b49b29535e489dbb',
    messagingSenderId: '186697788898',
    projectId: 'alfa-70c0a',
    authDomain: 'alfa-70c0a.firebaseapp.com',
    databaseURL:
        'https://alfa-70c0a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alfa-70c0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa-dm4Z0KepEdBlzKf7LaSvrNY3Ci7B8A',
    appId: '1:186697788898:android:fce3c8cfeacb8079489dbb',
    messagingSenderId: '186697788898',
    projectId: 'alfa-70c0a',
    databaseURL:
        'https://alfa-70c0a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alfa-70c0a.appspot.com',
  );
}
